### ISSUE TITLE
sys/sysctl.h：No such file or directory

### ISSUE THREAD

**Issue by liangzj** [froghui/yolanda#10]
老师你好，我刚从C学起，用cygwin与Clion再win7下搭建调试环境，运行时候报如下错误，是我还有库要加么？还是win7暂不支持？

![image](https://user-images.githubusercontent.com/11542059/68005747-3465ab80-fcb1-11e9-949a-31d3c83815ab.png)

**Comment by 562245918** [comment]
在linux下开发！

**Comment by froghui** [comment]
有同学建议，使用 Windows 系统 + CLion 的同学，可以在 Win10 应用商店中下载一个 Ubuntu 版本的 Windows 子系统，即 WSL，然后在 CLion 中配置工程的环境为 WSL 即可编译运行。

**Comment by Joeyscat** [comment]
直接注释掉也可编译成功
