### ISSUE TITLE
缺少config.h

### ISSUE THREAD

**Issue by wyf2317** [froghui/yolanda#11]
老师请问下lib/common.h 中包含的config.h在哪里？git项目中并没有找到该文件。能否提供一下

**Comment by froghui** [comment]
config.h是动态产生的，它是用来决定是使用epoll还是poll作为事件分发机制的。

专栏里第29讲有这方面的介绍。
configure_file(${CMAKE_CURRENT_SOURCE_DIR}/config.h.cmake
        ${CMAKE_CURRENT_BINARY_DIR}/include/config.h)
