### ISSUE TITLE
关于头文件的问题

### ISSUE THREAD

**Issue by ApprenticeYc** [froghui/yolanda#15]
老师你好，我想问一下我在敲网络编程代码的时候经常遇到缺少函数对应的头文件，有时候在ubuntu下编译经常一些问题半天解决不了，我想是不是先把所有的头文件都导入进来就像unp.h一样，关注于网络编程的本身，然后熟练了再去细节探索呢，小白哈

**Comment by froghui** [comment]
可以的，是一个好办法。

**Comment by ApprenticeYc** [comment]
非常感谢您的回复，我已经经过一个多星期的探索比较熟练了，另外重新学了linux下编译链接，对这些头文件和库的问题比较了解了。
上次在极客时间请问了您while(1)的问题，您非常快就回复了我，因为不知道怎么在上面回复，在此特别感谢哈！
现在基础篇快学习完了，有一些问题想向您再咨询下：
1、我本人经常用c++编程，有一些c代码的写法比较好奇，比如创建一个套接字int sockfd;sockfd = socket(...)，就是这种用法，想知道为什么不在定义时候就直接初始化，而要分开调用呢？
2、在客户端和服务器端通信的时候，服务器端代码创建两个缓冲区，如下：
char buf[BUFFER_SIZE];
...
    while (1) {
        bzero(buf, sizeof(buf));
        ...
        char send_line[MAXLINE];
        bzero(send_line, MAXLINE);
       ...
}
我省去了部分代码，想请教的就是，为什么不直接在while(1)循环外就定义两个缓冲区，然后进入while(1)直接调用bzero清空呢？
希望得到老师的解答！祝您身体健康，万事如意！

**Comment by froghui** [comment]
抱歉回复比较晚。

1. 我觉得是个人习惯问题；
2.我觉得你的做法更好。
