### ISSUE TITLE
这code写的是为了增加理解难度么。。。

### ISSUE THREAD

**Issue by zhanzju** [froghui/yolanda#16]
event_loop_channel_buffer_nolock 里fd完全没用到，code里也没什么有用的comment。。。越看越凌乱。。

**Comment by froghui** [comment]
fd没用到确实是一个失误，至于代码，我建议你和实战篇的讲义一起看，那里会有比较详细的解释。

**Comment by wangdach** [comment]
网络协议应该是跨主机通信必备的吧，目前用于网路编程开发效率高的语言是golang吗

**Comment by froghui** [comment]
开发语言效率高，如果指的是各种SDK，开发库比较齐备，开发起来效率比较高，那么首推Java和C/C++；如果是指运行效率高，C/C++, Rust, Golang都不错。
