### ISSUE TITLE
chap-34 执行出现 错误 Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by tobeiwanttobe** [froghui/yolanda#18]
前面的代码都运行过，没有问题。但是最后一讲的代码执行出现 Segmentation fault (core dumped)。
我是如此运行的：
./http_server01 
[msg] set epoll as dispatcher, main thread
[msg] add channel fd == 5, main thread
[msg] add channel fd == 6, main thread
[msg] event loop run, main thread

然后，无论是在浏览器还是在另一个终端尝试连接：
curl -v http://127.0.0.1:43211/
服务器端出现了 Segmentation fault (core dumped)
[msg] set epoll as dispatcher, main thread
[msg] add channel fd == 5, main thread
[msg] add channel fd == 6, main thread
[msg] event loop run, main thread
[msg] epoll_wait wakeup, main thread
[msg] get message channel fd==6 for read, main thread
[msg] activate channel fd == 6, revents=2, main thread
[msg] new connection established, socket == 7
[msg] connection completed
[msg] add channel fd == 7, main thread
[msg] epoll_wait wakeup, main thread
[msg] get message channel fd==7 for read, main thread
[msg] activate channel fd == 7, revents=2, main thread
[msg] get message from tcp connection connection-7
Segmentation fault (core dumped)
这时 客户端是：
   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 43211 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:43211
> User-Agent: curl/7.58.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host 127.0.0.1 left intact
curl: (52) Empty reply from server

**Comment by ZikeWang** [comment]
@tobeiwanttobe 请问最后怎么解决的？我也遇到了这个问题。
跑老师 @froghui  的源码，执行 ./http_server_test 也是 segmentation fault (core dump)，使用 curl 的话服务器端 http_server01 出现 core dump

**Comment by tobeiwanttobe** [comment]
@ZikeWang 你好，我并没有解决这个问题。

**Comment by ZikeWang** [comment]
@tobeiwanttobe 你好，我定位到问题在于 memmem 函数，全部换成 strstr 后解决，希望对你有帮助。

**Comment by tobeiwanttobe** [comment]
@ZikeWang 非常感谢，我根据你的提示，修改了代码，已经解决了这个问题。

**Comment by JessonKang** [comment]
> @tobeiwanttobe 你好，我定位到问题在于 memmem 函数，全部换成 strstr 后解决，希望对你有帮助。
你好，我把memmem改成strstr，执行 ./http_server01之后，客户端无论是telnet还是curl，只要客户端一输入，服务端就报segment fault。你是这样的情况吗？其它地方还有改动吗？
