### ISSUE TITLE
error: ‘for’ loop initial declarations are only allowed in C99 mode

### ISSUE THREAD

**Issue by linuxxiaoyu** [froghui/yolanda#2]
在build目录下make时，出现以下错误：

> /root/geekbang/yolanda/chap-5/tcpclient.c: In function ‘send_data’:
> /root/geekbang/yolanda/chap-5/tcpclient.c:8:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
>      for (int i = 0; i < MESSAGE_SIZE; i++) {
>      ^
> /root/geekbang/yolanda/chap-5/tcpclient.c:8:5: note: use option -std=c99 or -std=gnu99 to compile your code
> make[2]: *** [chap-5/CMakeFiles/tcpclient.dir/tcpclient.c.o] Error 1
> make[1]: *** [chap-5/CMakeFiles/tcpclient.dir/all] Error 2
> make: *** [all] Error 2

是否需要在CMakeLists.txt中添加以下选项呢？
`set(CMAKE_C_STANDARD 99)`

**Comment by kevinhuangwl** [comment]
我也遇到同样的问题，不知道要如何解决

/root/kevin/yolanda/lib/thread_pool.c: In function ‘thread_pool_start’:
/root/kevin/yolanda/lib/thread_pool.c:29:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int i = 0; i < threadPool->thread_number; ++i) {
     ^
/root/kevin/yolanda/lib/thread_pool.c:29:5: note: use option -std=c99 or -std=gnu99 to compile your code
make[2]: *** [lib/CMakeFiles/yolanda.dir/thread_pool.c.o] Error 1
make[1]: *** [lib/CMakeFiles/yolanda.dir/all] Error 2
make: *** [all] Error 2

**Comment by kevinhuangwl** [comment]
set(CMAKE_C_STANDARD 99) 可以解决

**Comment by froghui** [comment]
我这里好像不需要，和gcc的版本有关？

**Comment by froghui** [comment]
fixed
