### ISSUE TITLE
单独编译Chap-4代码编译异常

### ISSUE THREAD

**Issue by kevinhuangwl** [froghui/yolanda#4]
环境：CentOS7
操作过程：下载git项目后，直接在yolanda/chap-4下先执行cmake ./，然后再执行make，报以下错误：

[root@vm-centos chap-4]# make
[ 50%] Linking C executable make_socket
/usr/bin/ld: cannot find -lyolanda
collect2: error: ld returned 1 exit status
make[2]: *** [make_socket] Error 1
make[1]: *** [CMakeFiles/make_socket.dir/all] Error 2
make: *** [all] Error 2

**Comment by laohuijiadezhu** [comment]
我也遇见了相同的问题，请问如何解决的
