### ISSUE TITLE
httpRequest重置的问题

### ISSUE THREAD

**Issue by DQinYuan** [froghui/yolanda#7]
https://github.com/froghui/yolanda/blob/4d0630bffbdbe89ec75d6c5bde0658ce55ba233c/lib/http_server.c#L113-L116

httpRequest在任何情况都应该重置?而不是仅仅在连接关闭的时候，不然从浏览器每次访问的都是同一个页面（不管url是否一样）

```c
 if (http_request_close_connection(httpRequest)) { 
     tcp_connection_shutdown(tcpConnection); 
 } 
 http_request_reset(httpRequest); 
```

**Comment by froghui** [comment]
好像是的，你能提一个PR过来么？

**Comment by DQinYuan** [comment]
> 好像是的，你能提一个PR过来么？

好
